kind: pipeline
name: default
type: docker
steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: 35.173.247.9
    user: ubuntu
    key:
      from_secret: ssh-key
    port: 22
    command_timeout: 2m
    script: sudo -i
    source: 123.txt
    target: /home/deploy/web
    
      
