---
kind: pipeline
name: default
type: kubernetes
steps:
- name: build-news-api
  image: surendra268/gradlew-java-node_js
  commands:
    - npm install
    - cd server/
    - chmod +x ./gradlew
    - ./gradlew clean build
    
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    tags:
      - latest
      - build-v${DRONE_BUILD_NUMBER}
    repo: 613098030734.dkr.ecr.us-east-1.amazonaws.com/drone-trail
    registry: 613098030734.dkr.ecr.us-east-1.amazonaws.com
