kind: pipeline
name: default
type: docker
steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: 3.94.88.65
    user: ubuntu
    key:
      from_secret: ssh-key
    port: 22
    source: 123.txt, Dockerfile,testdrone.tar, file24
    target: home/
    script: 
      - ls 
