---
kind: pipeline
name: default
type: kubernetes
steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: 613098030734.dkr.ecr.us-east-1.amazonaws.com/drone-trail
    registry: 613098030734.dkr.ecr.us-east-1.amazonaws.com
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 54.163.159.201
    username: ubuntu
    port: 22
    key:
      from_secret: ssh-key
      script:
        - sudo chown ubuntu:ubuntu /var/run/docker.sock
        - sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 613098030734.dkr.ecr.us-east-1.amazonaws.com
        - sudo docker pull 613098030734.dkr.ecr.us-east-1.amazonaws.com/droneimage:latest
        - sudo docker run -idt -p 8080:80 --name apache 613098030734.dkr.ecr.us-east-1.amazonaws.com/droneimage:latest
        - ls
