kind: pipeline
name: default
type: docker
steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: 35.173.247.9
    user: ubuntu
    key:
      from_secret: ssh-key
    port: 22
    source: 123.txt, Dockerfile,testdrone.tar
    target: /home/
    script: 
      - sudo chmod +rwx /home
      - sudo chown ubuntu:ubuntu 
