---
kind: pipeline
name: default
type: kubernetes
steps:
- name: publish
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    tags:
      - latest
      - build-v${DRONE_BUILD_NUMBER}
    repo: 613098030734.dkr.ecr.us-east-1.amazonaws.com/drone-trail
    registry: 613098030734.dkr.ecr.us-east-1.amazonaws.com
- name: Helm upgrade
  image: ramalingam81/aws-kubectl-helm-kops
  environment:
    KOPS_STATE_STORE: "s3://k8s.keep-smiley.ga"
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  commands:
    - export KOPS_STATE_STORE=s3://k8s.keep-smiley.ga && kops export kubeconfig --name k8s.keep-smiley.ga --admin
    - chmod 600 /root/.kube/config
    - kubectl config set-context $(kubectl config current-context) --namespace=tvm
    - kubectl get deployments -n tvm -o wide
    - helm list
    #- helm history tvm-api
    #- helm upgrade tvm-api ./tvm-api/ --set image.tag=build-v${DRONE_BUILD_NUMBER}
    - helm install tvm-api ./tvm-api-helm/ --set image.tag=build-v${DRONE_BUILD_NUMBER}
    - helm history tvm-api
    - kubectl get deployments tvm-api -o wide
    
