kind: pipeline
name: default
type: docker
steps:
- name: upload
  image: plugins/s3
  settings:
    aws_assume_role: arn:aws:s3:::drone-trail
    bucket: drone-trail
    access_key:
      from_secret: access_key_id
    secret_key:
      from_secret: secret_key
    strip_prefix: .
    source: .
    target: /
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 54.209.92.141
    username: ubuntu
    key:
      from_secret: ssh-key
    port: 22
    script:
      #- ls
      
