kind: pipeline
name: default
type: docker
steps:
- name: scp files
  image: appleboy/drone-scp
  settings:
    host: 35.173.247.9
    user: ubuntu
    key:
      from_secret: ssh-key
    port: 22
    script: sudo chmod 777 /testdrone.tar
    source: testdrone.tar
    target: /
    
      
