apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdmsuiimage
  namespace: tdms
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: tdmsui-image
          image: 613098030734.dkr.ecr.us-east-1.amazonaws.com/txui:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tdmsui-service
  namespace: tdms
spec:
  type: NodePort
  selector:
    app: image
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
    nodePort: 30334
