package com.spxts.tdms.model;


public class TrasformerBushingNamePlate {
	
	
    private String bushingVoltage;
    
    private String id;
    
    private String autogenerated;
    
    private String yearMfg;
   
    private String tap;
   
    private String style;
    
    private  String drwg;
    
    private  String other;
  
    private  String soNum;
  
    private  String bushingSerialNum;
    
    private  String terminationId;
  
    private  String mfr;
   
    private  String type;
   
    private  String location;
    
    private  String clazz;
   
    private  String catalogNum;
  
    private  String c1Pf;
   
    private  String c1Cap;
   
    private  String c2Pf;

    private  String c2Cap;
   
    private  String kv;
    
    private  String amps;
    
    private  String bil;
    
   private  String status;
   
    private  String replacementDateUtc;

	public String getBushingVoltage() {
		return bushingVoltage;
	}

	public void setBushingVoltage(String bushingVoltage) {
		this.bushingVoltage = bushingVoltage;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAutogenerated() {
		return autogenerated;
	}

	public void setAutogenerated(String autogenerated) {
		this.autogenerated = autogenerated;
	}

	public String getYearMfg() {
		return yearMfg;
	}

	public void setYearMfg(String yearMfg) {
		this.yearMfg = yearMfg;
	}

	public String getTap() {
		return tap;
	}

	public void setTap(String tap) {
		this.tap = tap;
	}

	public String getStyle() {
		return style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	public String getDrwg() {
		return drwg;
	}

	public void setDrwg(String drwg) {
		this.drwg = drwg;
	}

	public String getOther() {
		return other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getSoNum() {
		return soNum;
	}

	public void setSoNum(String soNum) {
		this.soNum = soNum;
	}

	public String getBushingSerialNum() {
		return bushingSerialNum;
	}

	public void setBushingSerialNum(String bushingSerialNum) {
		this.bushingSerialNum = bushingSerialNum;
	}

	public String getTerminationId() {
		return terminationId;
	}

	public void setTerminationId(String terminationId) {
		this.terminationId = terminationId;
	}

	public String getMfr() {
		return mfr;
	}

	public void setMfr(String mfr) {
		this.mfr = mfr;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getClazz() {
		return clazz;
	}

	public void setClazz(String clazz) {
		this.clazz = clazz;
	}

	public String getCatalogNum() {
		return catalogNum;
	}

	public void setCatalogNum(String catalogNum) {
		this.catalogNum = catalogNum;
	}

	public String getC1Pf() {
		return c1Pf;
	}

	public void setC1Pf(String c1Pf) {
		this.c1Pf = c1Pf;
	}

	public String getC1Cap() {
		return c1Cap;
	}

	public void setC1Cap(String c1Cap) {
		this.c1Cap = c1Cap;
	}

	public String getC2Pf() {
		return c2Pf;
	}

	public void setC2Pf(String c2Pf) {
		this.c2Pf = c2Pf;
	}

	public String getC2Cap() {
		return c2Cap;
	}

	public void setC2Cap(String c2Cap) {
		this.c2Cap = c2Cap;
	}

	public String getKv() {
		return kv;
	}

	public void setKv(String kv) {
		this.kv = kv;
	}

	public String getAmps() {
		return amps;
	}

	public void setAmps(String amps) {
		this.amps = amps;
	}

	public String getBil() {
		return bil;
	}

	public void setBil(String bil) {
		this.bil = bil;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getReplacementDateUtc() {
		return replacementDateUtc;
	}

	public void setReplacementDateUtc(String replacementDateUtc) {
		this.replacementDateUtc = replacementDateUtc;
	}

}
