apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdmsimage
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: tdms-image
          image: 613098030734.dkr.ecr.us-east-1.amazonaws.com/drone-trail:latest
          ports:
            - containerPort: 8080

-----

apiVersion: v1
kind: Service
metadata:
  name: tdms-service
spec:
  selector:
    app: image
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
