apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdmsimage
  namespace: tdms
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: tdms-image
          image: 613098030734.dkr.ecr.us-east-1.amazonaws.com/drone-trail:latest
          ports:
            - containerPort: 1048

---
apiVersion: v1
kind: Service
metadata:
  name: tdms-service
  namespace: tdms
spec:
  type: NodePort
  selector:
    app: image
  ports:
  - protocol: TCP
    name: http
    port: 1048
    targetPort: 1048
    nodePort: 30333
