//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.15 at 01:24:59 PM IST 
//


package com.spxts.tdms.dobleUtils;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the testadminPackage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: testadminPackage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataModelR2 }
     * 
     */
    public DataModelR2 createDataModelR2() {
        return new DataModelR2();
    }

    /**
     * Create an instance of {@link TransformerType }
     * 
     */
    public TransformerType createTransformerType() {
        return new TransformerType();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnectionsLT }
     * 
     */
    public TransformerType.TurnsRatioConnectionsLT createTransformerTypeTurnsRatioConnectionsLT() {
        return new TransformerType.TurnsRatioConnectionsLT();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplateLT }
     * 
     */
    public TransformerType.TurnsRatioNameplateLT createTransformerTypeTurnsRatioNameplateLT() {
        return new TransformerType.TurnsRatioNameplateLT();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnectionsHT }
     * 
     */
    public TransformerType.TurnsRatioConnectionsHT createTransformerTypeTurnsRatioConnectionsHT() {
        return new TransformerType.TurnsRatioConnectionsHT();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplateHT }
     * 
     */
    public TransformerType.TurnsRatioNameplateHT createTransformerTypeTurnsRatioNameplateHT() {
        return new TransformerType.TurnsRatioNameplateHT();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnectionsLT }
     * 
     */
    public TransformerType.LvttratioConnectionsLT createTransformerTypeLvttratioConnectionsLT() {
        return new TransformerType.LvttratioConnectionsLT();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnectionsHT }
     * 
     */
    public TransformerType.LvttratioConnectionsHT createTransformerTypeLvttratioConnectionsHT() {
        return new TransformerType.LvttratioConnectionsHT();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnectionsLT }
     * 
     */
    public TransformerType.DobleRatioConnectionsLT createTransformerTypeDobleRatioConnectionsLT() {
        return new TransformerType.DobleRatioConnectionsLT();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindingsLT }
     * 
     */
    public TransformerType.DobleRatioCapWindingsLT createTransformerTypeDobleRatioCapWindingsLT() {
        return new TransformerType.DobleRatioCapWindingsLT();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnectionsHT }
     * 
     */
    public TransformerType.DobleRatioConnectionsHT createTransformerTypeDobleRatioConnectionsHT() {
        return new TransformerType.DobleRatioConnectionsHT();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindingsHT }
     * 
     */
    public TransformerType.DobleRatioCapWindingsHT createTransformerTypeDobleRatioCapWindingsHT() {
        return new TransformerType.DobleRatioCapWindingsHT();
    }

    /**
     * Create an instance of {@link TransformerType.OverallTestSet }
     * 
     */
    public TransformerType.OverallTestSet createTransformerTypeOverallTestSet() {
        return new TransformerType.OverallTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.OverallTestSet.OverallTest }
     * 
     */
    public TransformerType.OverallTestSet.OverallTest createTransformerTypeOverallTestSetOverallTest() {
        return new TransformerType.OverallTestSet.OverallTest();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnections }
     * 
     */
    public TransformerType.LvttratioConnections createTransformerTypeLvttratioConnections() {
        return new TransformerType.LvttratioConnections();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet }
     * 
     */
    public TransformerType.LvttratioTestSet createTransformerTypeLvttratioTestSet() {
        return new TransformerType.LvttratioTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest createTransformerTypeLvttratioTestSetLvttratioTest() {
        return new TransformerType.LvttratioTestSet.LvttratioTest();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields createTransformerTypeLvttratioTestSetLvttratioTestRatioTestFields() {
        return new TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences createTransformerTypeLvttratioTestSetLvttratioTestRatioTestFieldsTcReferences() {
        return new TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet createTransformerTypeLvttratioTestSetLvttratioTestRatioTestFieldsTcReferencesTcReferenceSet() {
        return new TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnections }
     * 
     */
    public TransformerType.DobleRatioConnections createTransformerTypeDobleRatioConnections() {
        return new TransformerType.DobleRatioConnections();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindings }
     * 
     */
    public TransformerType.DobleRatioCapWindings createTransformerTypeDobleRatioCapWindings() {
        return new TransformerType.DobleRatioCapWindings();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplate }
     * 
     */
    public TransformerType.TurnsRatioNameplate createTransformerTypeTurnsRatioNameplate() {
        return new TransformerType.TurnsRatioNameplate();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnections }
     * 
     */
    public TransformerType.TurnsRatioConnections createTransformerTypeTurnsRatioConnections() {
        return new TransformerType.TurnsRatioConnections();
    }

    /**
     * Create an instance of {@link TransformerType.Tapchangers }
     * 
     */
    public TransformerType.Tapchangers createTransformerTypeTapchangers() {
        return new TransformerType.Tapchangers();
    }

    /**
     * Create an instance of {@link TransformerType.ManualData }
     * 
     */
    public TransformerType.ManualData createTransformerTypeManualData() {
        return new TransformerType.ManualData();
    }

    /**
     * Create an instance of {@link TransformerType.ManualData.ManualConnectionTest }
     * 
     */
    public TransformerType.ManualData.ManualConnectionTest createTransformerTypeManualDataManualConnectionTest() {
        return new TransformerType.ManualData.ManualConnectionTest();
    }

    /**
     * Create an instance of {@link TransformerType.DemagnetizationTestSet }
     * 
     */
    public TransformerType.DemagnetizationTestSet createTransformerTypeDemagnetizationTestSet() {
        return new TransformerType.DemagnetizationTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding3 }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding3 createTransformerTypeM7WindingResistanceTestsWinding3() {
        return new TransformerType.M7WindingResistanceTestsWinding3();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding2 }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding2 createTransformerTypeM7WindingResistanceTestsWinding2() {
        return new TransformerType.M7WindingResistanceTestsWinding2();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding1 }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding1 createTransformerTypeM7WindingResistanceTestsWinding1() {
        return new TransformerType.M7WindingResistanceTestsWinding1();
    }

    /**
     * Create an instance of {@link TransformerType.SurgeArresterTestSet }
     * 
     */
    public TransformerType.SurgeArresterTestSet createTransformerTypeSurgeArresterTestSet() {
        return new TransformerType.SurgeArresterTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.SurgeArresterTestSet.SurgeArresterTest }
     * 
     */
    public TransformerType.SurgeArresterTestSet.SurgeArresterTest createTransformerTypeSurgeArresterTestSetSurgeArresterTest() {
        return new TransformerType.SurgeArresterTestSet.SurgeArresterTest();
    }

    /**
     * Create an instance of {@link TransformerType.Arresters }
     * 
     */
    public TransformerType.Arresters createTransformerTypeArresters() {
        return new TransformerType.Arresters();
    }

    /**
     * Create an instance of {@link TransformerType.BushingDesignations }
     * 
     */
    public TransformerType.BushingDesignations createTransformerTypeBushingDesignations() {
        return new TransformerType.BushingDesignations();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet createTransformerTypeExcitingCurrentTestSet() {
        return new TransformerType.ExcitingCurrentTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest createTransformerTypeExcitingCurrentTestSetExcitingCurrentTest() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestTcReferences() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestTcReferencesTcReferenceSet() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet();
    }

    /**
     * Create an instance of {@link TransformerType.M7BushingTestSet }
     * 
     */
    public TransformerType.M7BushingTestSet createTransformerTypeM7BushingTestSet() {
        return new TransformerType.M7BushingTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.M7BushingTestSet.M7BushingTest }
     * 
     */
    public TransformerType.M7BushingTestSet.M7BushingTest createTransformerTypeM7BushingTestSetM7BushingTest() {
        return new TransformerType.M7BushingTestSet.M7BushingTest();
    }

    /**
     * Create an instance of {@link TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet }
     * 
     */
    public TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet createTransformerTypeM7BushingTestSetM7BushingTestBushingTestResultsSet() {
        return new TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet();
    }

    /**
     * Create an instance of {@link TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults }
     * 
     */
    public TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults createTransformerTypeM7BushingTestSetM7BushingTestBushingTestResultsSetBushingTestResults() {
        return new TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults();
    }

    /**
     * Create an instance of {@link DataModelR2 .DtaSessions }
     * 
     */
    public DataModelR2 .DtaSessions createDataModelR2DtaSessions() {
        return new DataModelR2 .DtaSessions();
    }

    /**
     * Create an instance of {@link TransformerTemplateType }
     * 
     */
    public TransformerTemplateType createTransformerTemplateType() {
        return new TransformerTemplateType();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.TapchangerNameplates }
     * 
     */
    public TransformerTemplateType.TapchangerNameplates createTransformerTemplateTypeTapchangerNameplates() {
        return new TransformerTemplateType.TapchangerNameplates();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates createTransformerTemplateTypeLeakageReactanceNameplates() {
        return new TransformerTemplateType.LeakageReactanceNameplates();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate createTransformerTemplateTypeLeakageReactanceNameplatesLeakageReactanceNameplate() {
        return new TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences createTransformerTemplateTypeLeakageReactanceNameplatesLeakageReactanceNameplateTcReferences() {
        return new TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet createTransformerTemplateTypeLeakageReactanceNameplatesLeakageReactanceNameplateTcReferencesTcReferenceSet() {
        return new TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.ArresterNameplates }
     * 
     */
    public TransformerTemplateType.ArresterNameplates createTransformerTemplateTypeArresterNameplates() {
        return new TransformerTemplateType.ArresterNameplates();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.BushingNameplates }
     * 
     */
    public TransformerTemplateType.BushingNameplates createTransformerTemplateTypeBushingNameplates() {
        return new TransformerTemplateType.BushingNameplates();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.BushingNameplates.BushingNameplate }
     * 
     */
    public TransformerTemplateType.BushingNameplates.BushingNameplate createTransformerTemplateTypeBushingNameplatesBushingNameplate() {
        return new TransformerTemplateType.BushingNameplates.BushingNameplate();
    }

    /**
     * Create an instance of {@link AdminDataType }
     * 
     */
    public AdminDataType createAdminDataType() {
        return new AdminDataType();
    }

    /**
     * Create an instance of {@link TransformerType.TestAdminData }
     * 
     */
    public TransformerType.TestAdminData createTransformerTypeTestAdminData() {
        return new TransformerType.TestAdminData();
    }

    /**
     * Create an instance of {@link TransformerType.TestConditions }
     * 
     */
    public TransformerType.TestConditions createTransformerTypeTestConditions() {
        return new TransformerType.TestConditions();
    }

    /**
     * Create an instance of {@link TransformerType.WindingResistanceWindingDetail }
     * 
     */
    public TransformerType.WindingResistanceWindingDetail createTransformerTypeWindingResistanceWindingDetail() {
        return new TransformerType.WindingResistanceWindingDetail();
    }

    /**
     * Create an instance of {@link TransformerType.DfrTestSet }
     * 
     */
    public TransformerType.DfrTestSet createTransformerTypeDfrTestSet() {
        return new TransformerType.DfrTestSet();
    }

    /**
     * Create an instance of {@link TransformerType.WaterContent }
     * 
     */
    public TransformerType.WaterContent createTransformerTypeWaterContent() {
        return new TransformerType.WaterContent();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentConnections }
     * 
     */
    public TransformerType.ExcitingCurrentConnections createTransformerTypeExcitingCurrentConnections() {
        return new TransformerType.ExcitingCurrentConnections();
    }

    /**
     * Create an instance of {@link TransformerType.TransformerLayout }
     * 
     */
    public TransformerType.TransformerLayout createTransformerTypeTransformerLayout() {
        return new TransformerType.TransformerLayout();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnectionsLT.RatioConnectionFields }
     * 
     */
    public TransformerType.TurnsRatioConnectionsLT.RatioConnectionFields createTransformerTypeTurnsRatioConnectionsLTRatioConnectionFields() {
        return new TransformerType.TurnsRatioConnectionsLT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplateLT.TurnsRatioNameplateFields }
     * 
     */
    public TransformerType.TurnsRatioNameplateLT.TurnsRatioNameplateFields createTransformerTypeTurnsRatioNameplateLTTurnsRatioNameplateFields() {
        return new TransformerType.TurnsRatioNameplateLT.TurnsRatioNameplateFields();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnectionsHT.RatioConnectionFields }
     * 
     */
    public TransformerType.TurnsRatioConnectionsHT.RatioConnectionFields createTransformerTypeTurnsRatioConnectionsHTRatioConnectionFields() {
        return new TransformerType.TurnsRatioConnectionsHT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplateHT.TurnsRatioNameplateFields }
     * 
     */
    public TransformerType.TurnsRatioNameplateHT.TurnsRatioNameplateFields createTransformerTypeTurnsRatioNameplateHTTurnsRatioNameplateFields() {
        return new TransformerType.TurnsRatioNameplateHT.TurnsRatioNameplateFields();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnectionsLT.RatioConnectionFields }
     * 
     */
    public TransformerType.LvttratioConnectionsLT.RatioConnectionFields createTransformerTypeLvttratioConnectionsLTRatioConnectionFields() {
        return new TransformerType.LvttratioConnectionsLT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnectionsHT.RatioConnectionFields }
     * 
     */
    public TransformerType.LvttratioConnectionsHT.RatioConnectionFields createTransformerTypeLvttratioConnectionsHTRatioConnectionFields() {
        return new TransformerType.LvttratioConnectionsHT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnectionsLT.RatioConnectionFields }
     * 
     */
    public TransformerType.DobleRatioConnectionsLT.RatioConnectionFields createTransformerTypeDobleRatioConnectionsLTRatioConnectionFields() {
        return new TransformerType.DobleRatioConnectionsLT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindingsLT.DobleRatioCapWindingFields }
     * 
     */
    public TransformerType.DobleRatioCapWindingsLT.DobleRatioCapWindingFields createTransformerTypeDobleRatioCapWindingsLTDobleRatioCapWindingFields() {
        return new TransformerType.DobleRatioCapWindingsLT.DobleRatioCapWindingFields();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnectionsHT.RatioConnectionFields }
     * 
     */
    public TransformerType.DobleRatioConnectionsHT.RatioConnectionFields createTransformerTypeDobleRatioConnectionsHTRatioConnectionFields() {
        return new TransformerType.DobleRatioConnectionsHT.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindingsHT.DobleRatioCapWindingFields }
     * 
     */
    public TransformerType.DobleRatioCapWindingsHT.DobleRatioCapWindingFields createTransformerTypeDobleRatioCapWindingsHTDobleRatioCapWindingFields() {
        return new TransformerType.DobleRatioCapWindingsHT.DobleRatioCapWindingFields();
    }

    /**
     * Create an instance of {@link TransformerType.OverallTestSet.OverallTest.IwcData }
     * 
     */
    public TransformerType.OverallTestSet.OverallTest.IwcData createTransformerTypeOverallTestSetOverallTestIwcData() {
        return new TransformerType.OverallTestSet.OverallTest.IwcData();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioConnections.RatioConnectionFields }
     * 
     */
    public TransformerType.LvttratioConnections.RatioConnectionFields createTransformerTypeLvttratioConnectionsRatioConnectionFields() {
        return new TransformerType.LvttratioConnections.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest.Cablestates }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest.Cablestates createTransformerTypeLvttratioTestSetLvttratioTestCablestates() {
        return new TransformerType.LvttratioTestSet.LvttratioTest.Cablestates();
    }

    /**
     * Create an instance of {@link TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet.TcReference }
     * 
     */
    public TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet.TcReference createTransformerTypeLvttratioTestSetLvttratioTestRatioTestFieldsTcReferencesTcReferenceSetTcReference() {
        return new TransformerType.LvttratioTestSet.LvttratioTest.RatioTestFields.TcReferences.TcReferenceSet.TcReference();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioConnections.RatioConnectionFields }
     * 
     */
    public TransformerType.DobleRatioConnections.RatioConnectionFields createTransformerTypeDobleRatioConnectionsRatioConnectionFields() {
        return new TransformerType.DobleRatioConnections.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.DobleRatioCapWindings.DobleRatioCapWindingFields }
     * 
     */
    public TransformerType.DobleRatioCapWindings.DobleRatioCapWindingFields createTransformerTypeDobleRatioCapWindingsDobleRatioCapWindingFields() {
        return new TransformerType.DobleRatioCapWindings.DobleRatioCapWindingFields();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioNameplate.TurnsRatioNameplateFields }
     * 
     */
    public TransformerType.TurnsRatioNameplate.TurnsRatioNameplateFields createTransformerTypeTurnsRatioNameplateTurnsRatioNameplateFields() {
        return new TransformerType.TurnsRatioNameplate.TurnsRatioNameplateFields();
    }

    /**
     * Create an instance of {@link TransformerType.TurnsRatioConnections.RatioConnectionFields }
     * 
     */
    public TransformerType.TurnsRatioConnections.RatioConnectionFields createTransformerTypeTurnsRatioConnectionsRatioConnectionFields() {
        return new TransformerType.TurnsRatioConnections.RatioConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.Tapchangers.Tapchanger }
     * 
     */
    public TransformerType.Tapchangers.Tapchanger createTransformerTypeTapchangersTapchanger() {
        return new TransformerType.Tapchangers.Tapchanger();
    }

    /**
     * Create an instance of {@link TransformerType.ManualData.ManualConnectionTest.ManualConnectionFields }
     * 
     */
    public TransformerType.ManualData.ManualConnectionTest.ManualConnectionFields createTransformerTypeManualDataManualConnectionTestManualConnectionFields() {
        return new TransformerType.ManualData.ManualConnectionTest.ManualConnectionFields();
    }

    /**
     * Create an instance of {@link TransformerType.DemagnetizationTestSet.DemagnetizationConnections }
     * 
     */
    public TransformerType.DemagnetizationTestSet.DemagnetizationConnections createTransformerTypeDemagnetizationTestSetDemagnetizationConnections() {
        return new TransformerType.DemagnetizationTestSet.DemagnetizationConnections();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding3 .M7WindingResistanceConnections }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding3 .M7WindingResistanceConnections createTransformerTypeM7WindingResistanceTestsWinding3M7WindingResistanceConnections() {
        return new TransformerType.M7WindingResistanceTestsWinding3 .M7WindingResistanceConnections();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding2 .M7WindingResistanceConnections }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding2 .M7WindingResistanceConnections createTransformerTypeM7WindingResistanceTestsWinding2M7WindingResistanceConnections() {
        return new TransformerType.M7WindingResistanceTestsWinding2 .M7WindingResistanceConnections();
    }

    /**
     * Create an instance of {@link TransformerType.M7WindingResistanceTestsWinding1 .M7WindingResistanceConnections }
     * 
     */
    public TransformerType.M7WindingResistanceTestsWinding1 .M7WindingResistanceConnections createTransformerTypeM7WindingResistanceTestsWinding1M7WindingResistanceConnections() {
        return new TransformerType.M7WindingResistanceTestsWinding1 .M7WindingResistanceConnections();
    }

    /**
     * Create an instance of {@link TransformerType.SurgeArresterTestSet.SurgeArresterTest.IwcData }
     * 
     */
    public TransformerType.SurgeArresterTestSet.SurgeArresterTest.IwcData createTransformerTypeSurgeArresterTestSetSurgeArresterTestIwcData() {
        return new TransformerType.SurgeArresterTestSet.SurgeArresterTest.IwcData();
    }

    /**
     * Create an instance of {@link TransformerType.Arresters.Arrester }
     * 
     */
    public TransformerType.Arresters.Arrester createTransformerTypeArrestersArrester() {
        return new TransformerType.Arresters.Arrester();
    }

    /**
     * Create an instance of {@link TransformerType.BushingDesignations.Bushing }
     * 
     */
    public TransformerType.BushingDesignations.Bushing createTransformerTypeBushingDesignationsBushing() {
        return new TransformerType.BushingDesignations.Bushing();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.IwcData }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.IwcData createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestIwcData() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.IwcData();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.LinefreqTestVoltages }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.LinefreqTestVoltages createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestLinefreqTestVoltages() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.LinefreqTestVoltages();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.ExcitingCurrentFields }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.ExcitingCurrentFields createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestExcitingCurrentFields() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.ExcitingCurrentFields();
    }

    /**
     * Create an instance of {@link TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet.TcReference }
     * 
     */
    public TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet.TcReference createTransformerTypeExcitingCurrentTestSetExcitingCurrentTestTcReferencesTcReferenceSetTcReference() {
        return new TransformerType.ExcitingCurrentTestSet.ExcitingCurrentTest.TcReferences.TcReferenceSet.TcReference();
    }

    /**
     * Create an instance of {@link TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults.IwcData }
     * 
     */
    public TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults.IwcData createTransformerTypeM7BushingTestSetM7BushingTestBushingTestResultsSetBushingTestResultsIwcData() {
        return new TransformerType.M7BushingTestSet.M7BushingTest.BushingTestResultsSet.BushingTestResults.IwcData();
    }

    /**
     * Create an instance of {@link DataModelR2 .DtaSessions.DtaSession }
     * 
     */
    public DataModelR2 .DtaSessions.DtaSession createDataModelR2DtaSessionsDtaSession() {
        return new DataModelR2 .DtaSessions.DtaSession();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.HVWindingDetails }
     * 
     */
    public TransformerTemplateType.HVWindingDetails createTransformerTemplateTypeHVWindingDetails() {
        return new TransformerTemplateType.HVWindingDetails();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LVWindingDetails }
     * 
     */
    public TransformerTemplateType.LVWindingDetails createTransformerTemplateTypeLVWindingDetails() {
        return new TransformerTemplateType.LVWindingDetails();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.TVWindingDetails }
     * 
     */
    public TransformerTemplateType.TVWindingDetails createTransformerTemplateTypeTVWindingDetails() {
        return new TransformerTemplateType.TVWindingDetails();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.TapchangerNameplates.TapchangerNameplate }
     * 
     */
    public TransformerTemplateType.TapchangerNameplates.TapchangerNameplate createTransformerTemplateTypeTapchangerNameplatesTapchangerNameplate() {
        return new TransformerTemplateType.TapchangerNameplates.TapchangerNameplate();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.LrFields }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.LrFields createTransformerTemplateTypeLeakageReactanceNameplatesLeakageReactanceNameplateLrFields() {
        return new TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.LrFields();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet.TcReference }
     * 
     */
    public TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet.TcReference createTransformerTemplateTypeLeakageReactanceNameplatesLeakageReactanceNameplateTcReferencesTcReferenceSetTcReference() {
        return new TransformerTemplateType.LeakageReactanceNameplates.LeakageReactanceNameplate.TcReferences.TcReferenceSet.TcReference();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.ArresterNameplates.ArresterNameplate }
     * 
     */
    public TransformerTemplateType.ArresterNameplates.ArresterNameplate createTransformerTemplateTypeArresterNameplatesArresterNameplate() {
        return new TransformerTemplateType.ArresterNameplates.ArresterNameplate();
    }

    /**
     * Create an instance of {@link TransformerTemplateType.BushingNameplates.BushingNameplate.BushingDimensions }
     * 
     */
    public TransformerTemplateType.BushingNameplates.BushingNameplate.BushingDimensions createTransformerTemplateTypeBushingNameplatesBushingNameplateBushingDimensions() {
        return new TransformerTemplateType.BushingNameplates.BushingNameplate.BushingDimensions();
    }

}
